ENT.Base 			= "npc_vj_paranoia_zombie"
ENT.Type 			= "ai"
ENT.PrintName 		= "Zombie"
ENT.Author 			= "Warkin"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Purpose 		= "Spawn it and fight with it!"
ENT.Instructions 	= "Click on the spawnicon to spawn it."